# Pact verify workflow
#
# This workflow asserts that Pact contract tests are valid against this
# codebase. It is trigged when changes are made to this project and it
# is explicitly called by GDS API Adapters when changes are made there.

name: Run Pact tests

on:
  pull_request:
  push:
  workflow_call:
    inputs:
      # what branch or Git SHA to clone this app with, only applies when
      # called as a workflow, so current commit applies to push/pull requests
      commitish:
        required: false
        type: string
        default: main
      pact_consumer_version:
        required: true
        type: string

jobs:
  pact_verify:
    name: Verify pact tests
    runs-on: ubuntu-latest
    env:
      PACT_CONSUMER_VERSION: ${{ inputs.pact_consumer_version || 'branch-main' }}
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v3
        with:
          repository: alphagov/collections
          ref: ${{ inputs.commitish || github.sha }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rake pact:verify
